// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by go run cmd/llvmplugin/cpufeatures; DO NOT EDIT.

package main

import "fmt"

// Explicit aliases preserve the existing lowering policy without accepting
// future AVX512 extensions through a prefix match.
func goALLCCPUProfile(arch, feature string) string {
	if arch != "amd64" {
		return ""
	}
	switch feature {
	case "AVX", "AVXAES", "VAES":
		return "x86.avx"
	case "AVX2", "AVXVNNI":
		return "x86.avx2"
	case "AVX512", "AVX512F", "AVX512CD", "AVX512BW", "AVX512DQ", "AVX512VL", "AVX512GFNI", "AVX512VBMI2", "AVX512VNNI", "AVX512VAES", "AVX512VPCLMULQDQ":
		return "x86.avx512"
	case "AVX512BITALG":
		return "x86.avx512bitalg"
	case "AVX512VPOPCNTDQ":
		return "x86.avx512vpopcntdq"
	case "FMA":
		return "x86.fma"
	case "AVX512VBMI":
		return "x86.avx512vbmi"
	case "", "SHA":
		return ""
	default:
		panic(fmt.Sprintf("simdgen: unknown GoALLC CPU feature %q; update cmd/llvmplugin/cpufeatures", feature))
	}
}
