// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by simd/archsimd/_gen; DO NOT EDIT.

package runtime

import "internal/cpu"

const (
	goallcCPUFeatureSSE3             uint64 = 1 << 0
	goallcCPUFeatureSSSE3            uint64 = 1 << 1
	goallcCPUFeatureSSE41            uint64 = 1 << 2
	goallcCPUFeatureSSE42            uint64 = 1 << 3
	goallcCPUFeatureAVX              uint64 = 1 << 4
	goallcCPUFeatureFMA              uint64 = 1 << 5
	goallcCPUFeaturesInitialized     uint64 = 1 << 6
	goallcCPUFeaturePOPCNT           uint64 = 1 << 7
	goallcCPUFeatureARM64LSE         uint64 = 1 << 8
	goallcCPUFeatureAVX2             uint64 = 1 << 9
	goallcCPUFeatureAVX512           uint64 = 1 << 10
	goallcCPUFeatureAVX512BITALG     uint64 = 1 << 11
	goallcCPUFeatureAVX512VPOPCNTDQ  uint64 = 1 << 12
	goallcCPUFeatureAVX512VBMI       uint64 = 1 << 13
	goallcCPUFeatureARM64PMULL       uint64 = 1 << 14
	goallcCPUFeatureAVX512VBMI2      uint64 = 1 << 15
	goallcCPUFeatureAES              uint64 = 1 << 16
	goallcCPUFeaturePCLMULQDQ        uint64 = 1 << 17
	goallcCPUFeatureVAES             uint64 = 1 << 18
	goallcCPUFeatureVPCLMULQDQ       uint64 = 1 << 19
	goallcCPUFeatureAVX512VPCLMULQDQ uint64 = 1 << 20
	goallcCPUFeatureAVX512VAES       uint64 = 1 << 21
	goallcCPUFeatureAVX512GFNI       uint64 = 1 << 22
)

// Snapshot only effective Go booleans after internal/cpu applies GODEBUG.
// Do not apply the compiler's instruction-capability closure here.
func goallcCPUFeatureSnapshot() uint64 {
	var mask uint64
	switch GOARCH {
	case "386", "amd64":
		if cpu.X86.HasSSE3 {
			mask |= goallcCPUFeatureSSE3
		}
		if cpu.X86.HasSSSE3 {
			mask |= goallcCPUFeatureSSSE3
		}
		if cpu.X86.HasSSE41 {
			mask |= goallcCPUFeatureSSE41
		}
		if cpu.X86.HasSSE42 {
			mask |= goallcCPUFeatureSSE42
		}
		if cpu.X86.HasAVX {
			mask |= goallcCPUFeatureAVX
		}
		if cpu.X86.HasFMA {
			mask |= goallcCPUFeatureFMA
		}
		if cpu.X86.HasPOPCNT {
			mask |= goallcCPUFeaturePOPCNT
		}
		if cpu.X86.HasAVX2 {
			mask |= goallcCPUFeatureAVX2
		}
		if cpu.X86.HasAVX512 {
			mask |= goallcCPUFeatureAVX512
		}
		if cpu.X86.HasAVX512BITALG {
			mask |= goallcCPUFeatureAVX512BITALG
		}
		if cpu.X86.HasAVX512VPOPCNTDQ {
			mask |= goallcCPUFeatureAVX512VPOPCNTDQ
		}
		if cpu.X86.HasAVX512VBMI {
			mask |= goallcCPUFeatureAVX512VBMI
		}
		if cpu.X86.HasAVX512VBMI2 {
			mask |= goallcCPUFeatureAVX512VBMI2
		}
		if cpu.X86.HasAES {
			mask |= goallcCPUFeatureAES
		}
		if cpu.X86.HasPCLMULQDQ {
			mask |= goallcCPUFeaturePCLMULQDQ
		}
		if cpu.X86.HasVAES {
			mask |= goallcCPUFeatureVAES
		}
		if cpu.X86.HasVPCLMULQDQ {
			mask |= goallcCPUFeatureVPCLMULQDQ
		}
		if cpu.X86.HasAVX512VPCLMULQDQ {
			mask |= goallcCPUFeatureAVX512VPCLMULQDQ
		}
		if cpu.X86.HasAVX512VAES {
			mask |= goallcCPUFeatureAVX512VAES
		}
		if cpu.X86.HasAVX512GFNI {
			mask |= goallcCPUFeatureAVX512GFNI
		}
	case "arm64":
		if cpu.ARM64.HasATOMICS {
			mask |= goallcCPUFeatureARM64LSE
		}
		if cpu.ARM64.HasPMULL {
			mask |= goallcCPUFeatureARM64PMULL
		}
	default:
		return 0
	}
	return mask | goallcCPUFeaturesInitialized
}
