// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package goallccpu

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
)

const header = `// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by simd/archsimd/_gen; DO NOT EDIT.

`

type resolvedFeature struct {
	feature
	Mask    uint64
	Targets []string
}

func resolve(fs []feature, ps []profile, order []string) (map[string]resolvedFeature, error) {
	byName := make(map[string]feature)
	bits := make(map[uint]bool)
	for _, f := range fs {
		if f.Name == "" || f.Bit >= 64 || bits[f.Bit] {
			return nil, fmt.Errorf("invalid or duplicate feature bit: %+v", f)
		}
		if _, exists := byName[f.Name]; exists {
			return nil, fmt.Errorf("duplicate feature %s", f.Name)
		}
		if f.Name != "INITIALIZED" && ((f.Arch != "amd64" && f.Arch != "arm64") || f.Field == "") {
			return nil, fmt.Errorf("feature %s needs an architecture and runtime field", f.Name)
		}
		bits[f.Bit], byName[f.Name] = true, f
	}
	resolved := make(map[string]resolvedFeature)
	visiting := make(map[string]bool)
	var visit func(string) (resolvedFeature, error)
	visit = func(name string) (resolvedFeature, error) {
		if r, ok := resolved[name]; ok {
			return r, nil
		}
		f, ok := byName[name]
		if !ok || visiting[name] {
			return resolvedFeature{}, fmt.Errorf("unknown or cyclic capability %s", name)
		}
		visiting[name] = true
		r := resolvedFeature{feature: f, Mask: uint64(1) << f.Bit}
		for _, dependency := range f.Provides {
			d, err := visit(dependency)
			if err != nil {
				return resolvedFeature{}, err
			}
			if d.Arch == "" || d.Arch != f.Arch {
				return resolvedFeature{}, fmt.Errorf("cross-architecture capability %s -> %s", name, dependency)
			}
			r.Mask |= d.Mask
			for _, target := range d.Targets {
				if !slices.Contains(r.Targets, target) {
					r.Targets = append(r.Targets, target)
				}
			}
		}
		for _, target := range f.LLVM {
			if !slices.Contains(r.Targets, target) {
				r.Targets = append(r.Targets, target)
			}
		}
		visiting[name] = false
		resolved[name] = r
		return r, nil
	}
	for _, f := range fs {
		if _, err := visit(f.Name); err != nil {
			return nil, err
		}
	}
	names, aliases, guards := map[string]bool{}, map[string]bool{}, map[string]bool{}
	for _, p := range ps {
		f, ok := resolved[p.Feature]
		if !ok || f.Arch == "" || len(f.Targets) == 0 || names[p.Name] {
			return nil, fmt.Errorf("invalid or duplicate profile %s", p.Name)
		}
		prefix := "x86."
		if f.Arch == "arm64" {
			prefix = "arm64."
		}
		if !strings.HasPrefix(p.Name, prefix) {
			return nil, fmt.Errorf("profile %s has wrong architecture", p.Name)
		}
		names[p.Name] = true
		if p.RuntimeGuard != "" {
			if guards[p.RuntimeGuard] {
				return nil, fmt.Errorf("duplicate runtime guard %s", p.RuntimeGuard)
			}
			guards[p.RuntimeGuard] = true
		}
		for _, alias := range p.SIMDAliases {
			if aliases[alias] {
				return nil, fmt.Errorf("duplicate SIMD alias %s", alias)
			}
			aliases[alias] = true
		}
	}
	for _, alias := range unprofiledSIMDAliases {
		if aliases[alias] {
			return nil, fmt.Errorf("SIMD alias %q is both profiled and unprofiled", alias)
		}
	}
	for _, name := range order {
		if !names[name] {
			return nil, fmt.Errorf("unknown or duplicate request profile %s", name)
		}
		delete(names, name)
	}
	if len(names) != 0 {
		return nil, fmt.Errorf("request order omits profiles")
	}
	return resolved, nil
}

func goProfileName(p profile) string {
	prefix := "goCPUProfile"
	if strings.HasPrefix(p.Name, "x86.") {
		prefix += "X86"
	}
	return prefix + p.Feature
}

func runtimeName(f feature) string {
	if f.Name == "INITIALIZED" {
		return "goallcCPUFeaturesInitialized"
	}
	return "goallcCPUFeature" + f.Name
}

func generatedFiles() (map[string][]byte, error) {
	resolved, err := resolve(features, profiles, requestOrder)
	if err != nil {
		return nil, err
	}
	files := make(map[string][]byte)
	var goData, defs, snapshot bytes.Buffer
	fmt.Fprint(&goData, header, "//go:build !compiler_bootstrap\n\npackage ssa\n\nconst (\n")
	fmt.Fprint(&defs, header, "// Runtime predicate bits are append-only; capability closure never changes them.\n#ifdef GOALLC_CPU_FEATURE\n")
	fmt.Fprint(&snapshot, header, "package runtime\n\nimport \"internal/cpu\"\n\nconst (\n")
	for _, f := range features {
		fmt.Fprintf(&defs, "GOALLC_CPU_FEATURE(%s, %d)\n", f.Name, f.Bit)
		fmt.Fprintf(&snapshot, "%s uint64 = 1 << %d\n", runtimeName(f), f.Bit)
	}
	fmt.Fprint(&defs, "#endif\n\n#ifdef GOALLC_CPU_BASELINE\n")
	for level := 2; level <= 4; level++ {
		var mask uint64
		var names []string
		for _, f := range features {
			if f.AMD64Level != 0 && f.AMD64Level <= level {
				mask |= uint64(1) << f.Bit
				names = append(names, "Feature"+f.Name)
			}
		}
		fmt.Fprintf(&goData, "llvmCPUBaselineV%d uint64 = %#x\n", level, mask)
		fmt.Fprintf(&defs, "GOALLC_CPU_BASELINE(V%d, %s)\n", level, strings.Join(names, " | "))
	}
	fmt.Fprintf(&goData, "llvmCPUBaselineLSE uint64 = %#x\n", resolved["ARM64LSE"].Mask)
	for _, p := range profiles {
		fmt.Fprintf(&goData, "%s = %q\n", goProfileName(p), p.Name)
	}
	fmt.Fprint(&goData, ")\n\nvar llvmCPUProfiles = [...]llvmCPUProfile{\n")
	fmt.Fprint(&defs, "#endif\n\n#ifdef GOALLC_CPU_PROFILE\n")
	for _, p := range profiles {
		f := resolved[p.Feature]
		fmt.Fprintf(&goData, "{name:%s, arch:%q, field:%q, runtimeGuard:%q, predicate:%#x, capabilities:%#x},\n", goProfileName(p), f.Arch, f.Field, p.RuntimeGuard, uint64(1)<<f.Bit, f.Mask)
		var caps []string
		for _, candidate := range features {
			if f.Mask&(uint64(1)<<candidate.Bit) != 0 {
				caps = append(caps, "Feature"+candidate.Name)
			}
		}
		targets := "+" + strings.Join(f.Targets, ",+")
		_, suffix, _ := strings.Cut(p.Name, ".")
		fmt.Fprintf(&defs, "GOALLC_CPU_PROFILE(%q, %q, %q, %q, Feature%s, %s)\n", p.Name, suffix, targets, f.Arch, f.Name, strings.Join(caps, " | "))
	}
	fmt.Fprint(&defs, "#endif\n")
	fmt.Fprint(&goData, "}\n\nvar llvmCPURequestOrder = [...]string{\n")
	for _, name := range requestOrder {
		fmt.Fprintf(&goData, "%q,\n", name)
	}
	fmt.Fprint(&goData, "}\n")
	fmt.Fprint(&snapshot, ")\n\n// Snapshot only effective Go booleans after internal/cpu applies GODEBUG.\n// Do not apply the compiler's instruction-capability closure here.\nfunc goallcCPUFeatureSnapshot() uint64 {\nvar mask uint64\nswitch GOARCH {\n")
	for _, arch := range []string{"amd64", "arm64"} {
		record := "X86"
		if arch == "amd64" {
			fmt.Fprint(&snapshot, "case \"386\", \"amd64\":\n")
		} else {
			fmt.Fprint(&snapshot, "case \"arm64\":\n")
			record = "ARM64"
		}
		for _, f := range features {
			if f.Arch == arch {
				fmt.Fprintf(&snapshot, "if cpu.%s.%s { mask |= %s }\n", record, f.Field, runtimeName(f))
			}
		}
	}
	fmt.Fprint(&snapshot, "default: return 0\n}\nreturn mask | goallcCPUFeaturesInitialized\n}\n")
	for name, data := range map[string][]byte{
		"src/cmd/compile/internal/ssa/ssa2llvm_cpu_profiles_gen.go": goData.Bytes(),
		"src/runtime/cpuflags_goallc_gen.go":                        snapshot.Bytes(),
	} {
		formatted, err := format.Source(data)
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", name, err)
		}
		files[name] = formatted
	}
	files["src/cmd/llvmplugin/GoALLCCPUFeatures.def"] = defs.Bytes()
	return files, nil
}

func sourceRoot() string {
	_, file, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(file), "../../../../../.."))
}

// Generate writes the committed tables, or checks them without writes.
// No XED or ARM ISA data is needed for this stage.
func Generate(root string, check bool) error {
	files, err := generatedFiles()
	if err != nil {
		return err
	}
	var names []string
	for name := range files {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		path := filepath.Join(root, name)
		if check {
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !bytes.Equal(data, files[name]) {
				return fmt.Errorf("%s is stale; regenerate with simd/archsimd/_gen", name)
			}
		} else if err := os.WriteFile(path, files[name], 0644); err != nil {
			return err
		}
	}
	return nil
}

// ProfileForSIMD maps the upstream operation feature to its reviewed LLVM
// lowering profile. It reads authoring data directly, not generated Go code.
func ProfileForSIMD(arch, name string) string {
	if arch != "amd64" {
		return ""
	}
	for _, p := range profiles {
		if slices.Contains(p.SIMDAliases, name) {
			return p.Name
		}
	}
	if slices.Contains(unprofiledSIMDAliases, name) {
		return ""
	}
	panic(fmt.Sprintf("simdgen: unknown GoALLC CPU feature %q; update _gen/internal/goallccpu", name))
}
