// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by go run cmd/llvmplugin/cpufeatures; DO NOT EDIT.

//go:build !compiler_bootstrap

package ssa

const (
	llvmCPUBaselineV2              uint64 = 0x8f
	llvmCPUBaselineV3              uint64 = 0x2bf
	llvmCPUBaselineV4              uint64 = 0x6bf
	llvmCPUBaselineLSE             uint64 = 0x100
	goCPUProfileX86SSE41                  = "x86.sse41"
	goCPUProfileX86AVX                    = "x86.avx"
	goCPUProfileX86AVX2                   = "x86.avx2"
	goCPUProfileX86AVX512                 = "x86.avx512"
	goCPUProfileX86AVX512BITALG           = "x86.avx512bitalg"
	goCPUProfileX86AVX512VPOPCNTDQ        = "x86.avx512vpopcntdq"
	goCPUProfileX86FMA                    = "x86.fma"
	goCPUProfileX86POPCNT                 = "x86.popcnt"
	goCPUProfileARM64LSE                  = "arm64.lse"
	goCPUProfileX86AVX512VBMI             = "x86.avx512vbmi"
)

var llvmCPUProfiles = [...]llvmCPUProfile{
	{name: goCPUProfileX86SSE41, arch: "amd64", field: "HasSSE41", runtimeGuard: "runtime.x86HasSSE41", predicate: 0x4, capabilities: 0x4},
	{name: goCPUProfileX86AVX, arch: "amd64", field: "HasAVX", runtimeGuard: "", predicate: 0x10, capabilities: 0x10},
	{name: goCPUProfileX86AVX2, arch: "amd64", field: "HasAVX2", runtimeGuard: "", predicate: 0x200, capabilities: 0x210},
	{name: goCPUProfileX86AVX512, arch: "amd64", field: "HasAVX512", runtimeGuard: "", predicate: 0x400, capabilities: 0x610},
	{name: goCPUProfileX86AVX512BITALG, arch: "amd64", field: "HasAVX512BITALG", runtimeGuard: "", predicate: 0x800, capabilities: 0xe10},
	{name: goCPUProfileX86AVX512VPOPCNTDQ, arch: "amd64", field: "HasAVX512VPOPCNTDQ", runtimeGuard: "", predicate: 0x1000, capabilities: 0x1610},
	{name: goCPUProfileX86FMA, arch: "amd64", field: "HasFMA", runtimeGuard: "runtime.x86HasFMA", predicate: 0x20, capabilities: 0x20},
	{name: goCPUProfileX86POPCNT, arch: "amd64", field: "HasPOPCNT", runtimeGuard: "runtime.x86HasPOPCNT", predicate: 0x80, capabilities: 0x80},
	{name: goCPUProfileARM64LSE, arch: "arm64", field: "HasATOMICS", runtimeGuard: "runtime.arm64HasATOMICS", predicate: 0x100, capabilities: 0x100},
	{name: goCPUProfileX86AVX512VBMI, arch: "amd64", field: "HasAVX512VBMI", runtimeGuard: "", predicate: 0x2000, capabilities: 0x2610},
}

var llvmCPURequestOrder = [...]string{
	"x86.fma",
	"x86.sse41",
	"x86.popcnt",
	"x86.avx",
	"x86.avx2",
	"x86.avx512",
	"x86.avx512bitalg",
	"x86.avx512vpopcntdq",
	"arm64.lse",
	"x86.avx512vbmi",
}

var llvmCPUOpProfiles = map[Op]string{
	OpFloor:                         goCPUProfileX86SSE41,
	OpCeil:                          goCPUProfileX86SSE41,
	OpTrunc:                         goCPUProfileX86SSE41,
	OpRoundToEven:                   goCPUProfileX86SSE41,
	OpFMA:                           goCPUProfileX86FMA,
	OpPopCount8:                     goCPUProfileX86POPCNT,
	OpPopCount16:                    goCPUProfileX86POPCNT,
	OpPopCount32:                    goCPUProfileX86POPCNT,
	OpPopCount64:                    goCPUProfileX86POPCNT,
	OpAtomicStore8Variant:           goCPUProfileARM64LSE,
	OpAtomicStore32Variant:          goCPUProfileARM64LSE,
	OpAtomicStore64Variant:          goCPUProfileARM64LSE,
	OpAtomicAdd32Variant:            goCPUProfileARM64LSE,
	OpAtomicAdd64Variant:            goCPUProfileARM64LSE,
	OpAtomicExchange8Variant:        goCPUProfileARM64LSE,
	OpAtomicExchange32Variant:       goCPUProfileARM64LSE,
	OpAtomicExchange64Variant:       goCPUProfileARM64LSE,
	OpAtomicAnd64valueVariant:       goCPUProfileARM64LSE,
	OpAtomicAnd32valueVariant:       goCPUProfileARM64LSE,
	OpAtomicAnd8valueVariant:        goCPUProfileARM64LSE,
	OpAtomicOr64valueVariant:        goCPUProfileARM64LSE,
	OpAtomicOr32valueVariant:        goCPUProfileARM64LSE,
	OpAtomicOr8valueVariant:         goCPUProfileARM64LSE,
	OpAtomicCompareAndSwap32Variant: goCPUProfileARM64LSE,
	OpAtomicCompareAndSwap64Variant: goCPUProfileARM64LSE,
}
