// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by simd/archsimd/_gen; DO NOT EDIT.

//go:build !compiler_bootstrap

package ssa

const (
	llvmCPUBaselineV2              uint64 = 0x8f
	llvmCPUBaselineV3              uint64 = 0x2bf
	llvmCPUBaselineV4              uint64 = 0x6bf
	llvmCPUBaselineLSE             uint64 = 0x100
	goCPUProfileX86SSE41                  = "x86.sse41"
	goCPUProfileX86AVX                    = "x86.avx"
	goCPUProfileX86AVX2                   = "x86.avx2"
	goCPUProfileX86AVX512                 = "x86.avx512"
	goCPUProfileX86AVX512BITALG           = "x86.avx512bitalg"
	goCPUProfileX86AVX512VPOPCNTDQ        = "x86.avx512vpopcntdq"
	goCPUProfileX86FMA                    = "x86.fma"
	goCPUProfileX86POPCNT                 = "x86.popcnt"
	goCPUProfileARM64LSE                  = "arm64.lse"
	goCPUProfileX86AVX512VBMI             = "x86.avx512vbmi"
	goCPUProfileARM64PMULL                = "arm64.pmull"
	goCPUProfileX86AVX512VBMI2            = "x86.avx512vbmi2"
)

var llvmCPUProfiles = [...]llvmCPUProfile{
	{name: goCPUProfileX86SSE41, arch: "amd64", field: "HasSSE41", runtimeGuard: "runtime.x86HasSSE41", capabilities: 0x4, targetFeatures: "+sse4.1"},
	{name: goCPUProfileX86AVX, arch: "amd64", field: "HasAVX", runtimeGuard: "", capabilities: 0x10, targetFeatures: "+avx"},
	{name: goCPUProfileX86AVX2, arch: "amd64", field: "HasAVX2", runtimeGuard: "", capabilities: 0x210, targetFeatures: "+avx,+avx2"},
	{name: goCPUProfileX86AVX512, arch: "amd64", field: "HasAVX512", runtimeGuard: "", capabilities: 0x610, targetFeatures: "+avx,+avx2,+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl"},
	{name: goCPUProfileX86AVX512BITALG, arch: "amd64", field: "HasAVX512BITALG", runtimeGuard: "", capabilities: 0xe10, targetFeatures: "+avx,+avx2,+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl,+avx512bitalg"},
	{name: goCPUProfileX86AVX512VPOPCNTDQ, arch: "amd64", field: "HasAVX512VPOPCNTDQ", runtimeGuard: "", capabilities: 0x1610, targetFeatures: "+avx,+avx2,+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl,+avx512vpopcntdq"},
	{name: goCPUProfileX86FMA, arch: "amd64", field: "HasFMA", runtimeGuard: "runtime.x86HasFMA", capabilities: 0x20, targetFeatures: "+fma"},
	{name: goCPUProfileX86POPCNT, arch: "amd64", field: "HasPOPCNT", runtimeGuard: "runtime.x86HasPOPCNT", capabilities: 0x80, targetFeatures: "+popcnt"},
	{name: goCPUProfileARM64LSE, arch: "arm64", field: "HasATOMICS", runtimeGuard: "runtime.arm64HasATOMICS", capabilities: 0x100, targetFeatures: "+lse"},
	{name: goCPUProfileX86AVX512VBMI, arch: "amd64", field: "HasAVX512VBMI", runtimeGuard: "", capabilities: 0x2610, targetFeatures: "+avx,+avx2,+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl,+avx512vbmi"},
	{name: goCPUProfileARM64PMULL, arch: "arm64", field: "HasPMULL", runtimeGuard: "", capabilities: 0x4000, targetFeatures: "+aes"},
	{name: goCPUProfileX86AVX512VBMI2, arch: "amd64", field: "HasAVX512VBMI2", runtimeGuard: "", capabilities: 0x8610, targetFeatures: "+avx,+avx2,+avx512f,+avx512cd,+avx512bw,+avx512dq,+avx512vl,+avx512vbmi2"},
}
