// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore

// Generate builtinlist.go from cmd/compile/internal/typecheck/_builtin/runtime.go.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var stdout = flag.Bool("stdout", false, "write to stdout instead of builtinlist.go")

func main() {
	flag.Parse()

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by mkbuiltin.go. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package goobj")

	mkbuiltin(&b)

	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if *stdout {
		_, err = os.Stdout.Write(out)
	} else {
		err = os.WriteFile("builtinlist.go", out, 0666)
	}
	if err != nil {
		log.Fatal(err)
	}
}

func mkbuiltin(w io.Writer) {
	const pkg = "runtime"
	fset := token.NewFileSet()
	path := filepath.Join("..", "..", "compile", "internal", "typecheck", "_builtin", "runtime.go")
	f, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		log.Fatal(err)
	}

	decls := make(map[string]bool)
	builtinIndex := 0
	var lateBuiltins []int

	fmt.Fprintf(w, "var builtins = [...]struct{ name string; abi int }{\n")
	for _, decl := range f.Decls {
		switch decl := decl.(type) {
		case *ast.FuncDecl:
			if decl.Recv != nil {
				log.Fatal("methods unsupported")
			}
			if decl.Body != nil {
				log.Fatal("unexpected function body")
			}
			declName := pkg + "." + decl.Name.Name
			decls[declName] = true
			fmt.Fprintf(w, "{%q, 1},\n", declName) // functions are ABIInternal (1)
			builtinIndex++
		case *ast.GenDecl:
			if decl.Tok == token.IMPORT {
				continue
			}
			if decl.Tok != token.VAR {
				log.Fatal("unhandled declaration kind: ", decl.Tok)
			}
			for _, spec := range decl.Specs {
				spec := spec.(*ast.ValueSpec)
				if len(spec.Values) != 0 {
					log.Fatal("unexpected values")
				}
				for _, name := range spec.Names {
					declName := pkg + "." + name.Name
					decls[declName] = true
					fmt.Fprintf(w, "{%q, 0},\n", declName) // variables are ABI0
					builtinIndex++
				}
			}
		default:
			log.Fatal("unhandled decl type: ", decl)
		}
	}

	// The list above only contains ones that are used by the frontend.
	// The backend may create more references of builtin functions.
	// We also want to include predefined types.
	// Add them.
	extras := append(fextras[:], enumerateBasicTypes()...)
	for _, b := range extras {
		prefix := ""
		if !strings.HasPrefix(b.name, "type:") {
			prefix = pkg + "."
		}
		name := prefix + b.name
		if decls[name] {
			log.Fatalf("%q already added -- mkbuiltin.go out of sync?", name)
		}
		fmt.Fprintf(w, "{%q, %d},\n", name, b.abi)
		if b.late {
			lateBuiltins = append(lateBuiltins, builtinIndex)
		}
		builtinIndex++
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "var lateBuiltins = [...]bool{")
	for _, i := range lateBuiltins {
		fmt.Fprintf(w, "%d: true,\n", i)
	}
	fmt.Fprintln(w, "}")
}

// enumerateBasicTypes returns the symbol names for basic types that are
// defined in the runtime and referenced in other packages.
// Needs to be kept in sync with reflect.go:WriteBasicTypes() and
// reflect.go:writeType() in the compiler.
func enumerateBasicTypes() []extra {
	names := [...]string{
		"int8", "uint8", "int16", "uint16",
		"int32", "uint32", "int64", "uint64",
		"float32", "float64", "complex64", "complex128",
		"unsafe.Pointer", "uintptr", "bool", "string", "error",
		"func(error) string"}
	result := []extra{}
	for _, n := range names {
		result = append(result, extra{name: "type:" + n, abi: 0})
		result = append(result, extra{name: "type:*" + n, abi: 0})
	}
	return result
}

type extra struct {
	name string
	abi  int
	late bool
}

var fextras = [...]extra{
	// compiler frontend inserted calls (sysfunc)
	{name: "deferproc", abi: 1},
	{name: "deferprocStack", abi: 1},
	{name: "deferreturn", abi: 1},
	{name: "newproc", abi: 1},
	{name: "panicoverflow", abi: 1},
	{name: "sigpanic", abi: 1},

	// compiler backend inserted calls
	{name: "gcWriteBarrier1", abi: 1, late: true},
	{name: "gcWriteBarrier2", abi: 1, late: true},
	{name: "gcWriteBarrier3", abi: 1, late: true},
	{name: "gcWriteBarrier4", abi: 1, late: true},
	{name: "gcWriteBarrier5", abi: 1, late: true},
	{name: "gcWriteBarrier6", abi: 1, late: true},
	{name: "gcWriteBarrier7", abi: 1, late: true},
	{name: "gcWriteBarrier8", abi: 1, late: true},
	{name: "duffzero", abi: 1},
	{name: "duffcopy", abi: 1},

	// assembler backend inserted calls
	{name: "morestack", abi: 0, late: true},        // asm function, ABI0
	{name: "morestackc", abi: 0, late: true},       // asm function, ABI0
	{name: "morestack_noctxt", abi: 0, late: true}, // asm function, ABI0
	{name: "retpolineAX", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineCX", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineDX", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineBX", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineBP", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineSI", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineDI", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineR8", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineR9", abi: 0},                  // asm function, ABI0, amd64 only
	{name: "retpolineR10", abi: 0},                 // asm function, ABI0, amd64 only
	{name: "retpolineR11", abi: 0},                 // asm function, ABI0, amd64 only
	{name: "retpolineR12", abi: 0},                 // asm function, ABI0, amd64 only
	{name: "retpolineR13", abi: 0},                 // asm function, ABI0, amd64 only
	{name: "retpolineR14", abi: 0},                 // asm function, ABI0, amd64 only
	{name: "retpolineR15", abi: 0},                 // asm function, ABI0, amd64 only
	{name: "tls_g", abi: 0},                        // asm variable, amd64 and 386 only
}
